### ISSUE TITLE
Tab counts misleading when query is active

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#104]
Numbers remain when queries are still running after adding a detected field, label, pattern, or using the filter variables at the top.

<img width="684" alt="image" src="https://github.com/grafana/loki-explore/assets/109082771/f5c82418-2acc-4488-95e2-24d438fe5971">

Could we add a loading indicator instead of giving an incorrect count (which implies the query is done loading for that tab)

**Comment by ivanahuckova** [comment]
I think this will get fixed when https://github.com/grafana/explore-logs/issues/245 is implemented, so closing.
