### ISSUE TITLE
No labels for single cardinality aggregated labels

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#130]
https://obslogs.grafana-dev.net/a/grafana-lokiexplore-app/explore?logId=&var-fields=&var-filters=service_name%7C%3D%7Ccompactor&var-ds=jmaf_Ro4k&var-patterns=&var-lineFilter=&mode=logs&actionView=labels&var-logsFormat=%20%7C%20logfmt&var-labelBy=conprof

<img width="1723" alt="image" src="https://github.com/grafana/loki-explore/assets/109082771/e6cbcc53-aef4-438f-9fc7-f6670e9f0a6a">

Clicking "Add to filters" does nothing. Is there anyway we can prevent single-cardinality labels from displaying as an aggregation option in the first place?

**Comment by ivanahuckova** [comment]
Could be solved by detected_fields API, so let's check if this is an issue when https://github.com/grafana/explore-logs/issues/245.

If it doesn't solve, we should do the same as what we do with `duration`


![Image](https://github.com/grafana/explore-logs/assets/30407135/e3edd070-d250-44e9-84f9-2b39a0d98c21)

**Comment by gtk-grafana** [comment]
Closing, cannot reproduce anymore
