### ISSUE TITLE
Logs volume should not use parser if not needed

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/explore-logs#143]
@cyriltovena the largest query on service index page - to fetch to top services is not using any parser
<img width="1510" alt="image" src="https://github.com/grafana/loki-explore/assets/30407135/5290d576-86c8-4ced-92d6-afbd583d94f3">

However, on the service detail page, it would be more complex to determine whether we have some detected fields selected or not (if we need a parser to make query with detected fields work). Of course, it is doable, but considering at the moment, have a lot of issues with state, I would probably wait to resolve them and then optimize when this is more stable. 

So keeping this in `No Status`

Also more in https://raintank-corp.slack.com/archives/C05FWM2DN07/p1712171252433889?thread_ts=1712165843.027599&cid=C05FWM2DN07

**Comment by ivanahuckova** [comment]
Blocked by `detected_fields` PR and refactor of query creation logic.

**Comment by ivanahuckova** [comment]
Might be solved by #257

**Comment by gtk-grafana** [comment]
Should be fixed by https://github.com/grafana/explore-logs/pull/736
