### ISSUE TITLE
log level from metadata is hard to use

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#161]
Doesn't show as detected labels, but can be breakdown by it, can't be filtered via labels, but by fields only.

see https://admin-dev-us-central-0.grafana-dev.net/grafana/explore?schemaVersion=1&panes=%7B%224df%22:%7B%22datasource%22:%22loki-dev%22,%22queries%22:%5B%7B%22refId%22:%22logs%22,%22expr%22:%22sum%20by%20%28level%29%28count_over_time%28%7Bservice_name%3D%60pattern-ingester%60%7D%20%7C%3D%20%60%60%20%7C%20level%3D%5C%22error%5C%22%5B$__auto%5D%29%29%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-dev%22%7D,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&orgId=1

**Comment by ivanahuckova** [comment]
Is this same/similar as https://github.com/grafana/explore-logs/issues/209?

**Comment by matryer** [comment]
@cyriltovena we're closing this in favour of https://github.com/grafana/explore-logs/issues/310
