### ISSUE TITLE
Service selection: Use synchronized cross-hairs

### ISSUE THREAD

**Issue by zizzpudding** [grafana/explore-logs#207]
Synchronized cross-hairs will help users orient time frame and compare what's happening in different services at the same time. 
See Dashboard for this functionality 
![image](https://github.com/grafana/explore-logs/assets/573085/f75dad00-cf26-4bea-b062-2e92912e16df)

**Comment by ivanahuckova** [comment]
Implement following:
![Uploading image.png…]()
