### ISSUE TITLE
Clarify docs for docker compose set up

### ISSUE THREAD

**Issue by damjoy** [grafana/explore-logs#211]
Just checking but for Docker compose instructions, 
See https://github.com/grafana/explore-logs?tab=readme-ov-file#test-out-with-docker-compose

I see the following error, when attempting to spin up Grafana, Loki, and the Logs Explore App using the given compose file

```
[+] Building 0.0s (0/0)                                                                                                                                                                                     
unable to prepare context: path "./generator" not found
```
Can you double check this is correct? https://github.com/grafana/explore-logs/blob/main/docker-compose.yaml#L32
as I think there is an expectation that a generator directory already exists, that contains the Dockerfile file.

Thanks

**Comment by gtk-grafana** [comment]
Good catch, I can repro as well. Looks like the code is assuming you've already got the repo checked out in the working directory. 

You can workaround this by cloning this repo (e.g. `git clone https://github.com/grafana/explore-logs.git .`) into an empty directory, and then running `docker-compose up` for now.

Should be a quick fix, we'll close this out when a fix has been merged.
