### ISSUE TITLE
logs-generator bug-exited with code 1

### ISSUE THREAD

**Issue by damjoy** [grafana/explore-logs#215]
A follow on from https://github.com/grafana/explore-logs/issues/211

I ran the updated steps, but the generator app exits unexpectedly on setup,

```
explore-logs-generator-1  | exec /generator: exec format error
explore-logs-generator-1 exited with code 1
```
Only logs from the container:

```
docker logs -f c4054acdbe05
exec /generator: exec format error
```

I also, tried by cloning the repo as suggested (e.g. git clone https://github.com/grafana/explore-logs.git ) and running docker compose from the directory, the logs generator still exits with same:

`explore-logs-generator-1 exited with code 1`

![image](https://github.com/grafana/explore-logs/assets/72019484/b962a5f2-6e4e-40b2-8faf-7b0a2ddb1be5)

**Comment by ystkfujii** [comment]
I had the same problem.

In my case, the following steps solved the problem.

- Cloned the repo
- Rebuilt the image of the generator with `docker build -t generator:dev .`
- Rewrite the image of the generator in docker-compose.yaml to `generator:dev`

**Comment by cyriltovena** [comment]
Yeah ok this seems to be a architecture issue of the container build @svennergr we should try to use a multi-arch image.

**Comment by svennergr** [comment]
Hi @damjoy and @ystkfujii,

Especially #272 should have fixed this issue. Do you mind retesting if the bug still happens?

Thank you!

**Comment by damjoy** [comment]
@svennergr Thanks for looking at the bug, it is working as expected now :+1: 

![image](https://github.com/grafana/explore-logs/assets/72019484/44bf0e85-b171-453c-a221-f50528045f1b)
