### ISSUE TITLE
App does not display any services when using a different label for discover_service_name 

### ISSUE THREAD

**Issue by anandak** [grafana/explore-logs#227]
I am using the following in limits_config section of loki yaml since this is the only label that matches service name.
`discover_service_name: [role] `

I am able to see service_name in label browser in explore as seen below:
![image](https://github.com/grafana/explore-logs/assets/1454027/ec1372b2-dbb1-4687-8d13-0c15d6aa64ab)

The corresponding selector from above also displays logs and their volume correctly
![image](https://github.com/grafana/explore-logs/assets/1454027/bdee4b08-ffa7-45f6-9ff7-80776d0673ab)

But in the Explore Logs app, I do not see any services and using the same selector from above does not show any services.

![image](https://github.com/grafana/explore-logs/assets/1454027/97f3f7e4-2314-4294-899b-0458f0b70c82)
![image](https://github.com/grafana/explore-logs/assets/1454027/92dda746-74c0-4bb2-91bb-add10ffa6638)

**Comment by cyriltovena** [comment]
Are you using Loki 3.0 ?

**Comment by cyriltovena** [comment]
so I think we did not make the log volume endpoint enabled by default in 3.0. Working on fixing that for 3.1.

In the meantime please either add this to your loki config:

```yaml
limits_config:
  volume_enabled: true
```

And that should solve the issue.

**Comment by cyriltovena** [comment]
Related to https://github.com/grafana/explore-logs/issues/219

**Comment by anandak** [comment]
> so I think we did not make the log volume endpoint enabled by default in 3.0. Working on fixing that for 3.1.
> 
> In the meantime please either add this to your loki config:
> 
> ```yaml
> limits_config:
>   volume_enabled: true
> ```
> 
> And that should solve the issue.

@cyriltovena Thank you so much. This resolved the issue and I am able to discover services now! 
This is such a wonderful app especially for beginners who do not yet have their hands around LogQL. Thanks again.
