### ISSUE TITLE
[service selection] If there’s “too much data” we should not show this service/app/whatever

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#247]

**Comment by gtk-grafana** [comment]
@cyriltovena are you referring to the 504 response?
<img width="1728" alt="image" src="https://github.com/grafana/explore-logs/assets/109082771/df93abb1-78ee-4d81-aadc-dd38aa3b53a4">

Assuming so: in this case we are able to query the logs, but the volume aggregation fails. Do we want to hide the service?

Also, if we hide services that timeout, how will users know that they timed-out and they need to reduce their time range?

**Comment by gtk-grafana** [comment]
Oh I had missed the conversation in slack: https://raintank-corp.slack.com/archives/C05FWM2DN07/p1713970007926369

**Comment by L2D2Grafana** [comment]
Might be good to deprioritized this ticket and see if @cyriltovena is happy with [lazy loading](https://github.com/grafana/explore-logs/issues/248)

**Comment by cyriltovena** [comment]
@L2D2Grafana good call ! I think we're fine for now.
