### ISSUE TITLE
Add query header for all explore logs API calls

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#290]
We should add a `X-Query-Tags: explorelogs` headers to all requests coming from the app so that we can dissociate them from other experience.

This will help us identify problems with the app firing too much data for instance in the future and how our users is using the app.

**Comment by svennergr** [comment]
https://github.com/grafana/explore-logs/pull/291 will add the header for "queries", i.e. `/query` and `/query_range` API.

**Comment by svennergr** [comment]
https://github.com/grafana/explore-logs/pull/292 added tracking to all the other APIs.
