### ISSUE TITLE
papercut: back button

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#351]
Bruno: I selected hosted-grafana/grafana but realized that was wrong, clicked the back button and got booted back to the home page.

**Comment by zizzpudding** [comment]
This is a known issue, breadcrumbs haven't been implemented yet. This could also be solved by adding the history trail.

**Comment by gtk-grafana** [comment]
This can be implemented by wrapping each route with the `PluginPage` component. However it will require a bit of refactor to the index scene, since currently each breakdown scene is not a route.

**Comment by gtk-grafana** [comment]
I'd like to propose that this becomes a high priority.
