### ISSUE TITLE
bug: pattern UI graphs disappearing

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#355]
When switching windows or tabs all graph are disappearing.

<img width="2534" alt="image" src="https://github.com/grafana/explore-logs/assets/1053421/c3368f78-aa2e-4f87-8e10-584df63ff60a">

**Comment by gtk-grafana** [comment]
I can't reproduce this, can you provide some more info @cyriltovena?

**Comment by gtk-grafana** [comment]
I think this was the loki bug where the patterns was returning values with timestamps outside the requested time range. Closing
