### ISSUE TITLE
exp: move Log Volume graph into Logs tab

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#356]
move Log Volume graph into Logs tab.

* Could put it into Labels and Detected Fields too

Some other tabs provide a specialised Log Volume view:

<img width="2992" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/dc4a4990-4675-47b0-9c19-dad5cec7666a">

**Comment by gtk-grafana** [comment]
Closed by https://github.com/grafana/explore-logs/pull/369
