### ISSUE TITLE
patterns: allow 'Include' by multiple patterns

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#365]
The backend supports this: Include lines that match pattern A OR pattern B. This could be useful for including a handful of patterns as part of an investigation, i.e. "show me the warnings about disk size AND the auto-deleter errors."

@svennergr [proved it](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%228kc%22%3A%7B%22datasource%22%3A%22OP27Xzxnk%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22all%22%2C%22expr%22%3A%22sum%28count_over_time%28%7Bapp%3D%5C%22aggregator%5C%22%7D+%7C%3E+%60%3C_%3Efailed+to+push+aggregation+result%3C_%3E%60+or+%60%3C_%3Eprocessing+aggregation+result%3C_%3E%60+%5B%24__auto%5D%29%29%22%2C%22queryType%22%3A%22instant%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22OP27Xzxnk%22%7D%2C%22editorMode%22%3A%22code%22%7D%2C%7B%22refId%22%3A%22part1%22%2C%22expr%22%3A%22sum%28count_over_time%28%7Bapp%3D%5C%22aggregator%5C%22%7D+%7C%3E+%60%3C_%3Eprocessing+aggregation+result%3C_%3E%60+%5B%24__auto%5D%29%29%22%2C%22queryType%22%3A%22instant%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22OP27Xzxnk%22%7D%2C%22editorMode%22%3A%22code%22%7D%2C%7B%22refId%22%3A%22part2%22%2C%22expr%22%3A%22sum%28count_over_time%28%7Bapp%3D%5C%22aggregator%5C%22%7D+%7C%3E+%60%3C_%3Efailed+to+push+aggregation+result%3C_%3E%60+%5B%24__auto%5D%29%29%22%2C%22queryType%22%3A%22instant%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22OP27Xzxnk%22%7D%2C%22editorMode%22%3A%22code%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221716984875397%22%2C%22to%22%3A%221716984880397%22%7D%2C%22panelsState%22%3A%7B%22logs%22%3A%7B%22visualisationType%22%3A%22logs%22%7D%7D%7D%7D&orgId=1)

We should also adjust the experience such that clicking 'Include' just changes the state in place, but doesn't force you back to the Logs tab. So you can include a few and then go there yourself to see what it looks like.

**Comment by zizzpudding** [comment]
Some advice... Be careful with the wording.
With the statement, it could be misinterpreted as being show me all the log lines that contain both disk size warning and auto delete errors in the same long line.  - this could result in an empty set. 

 
"Show me log lines that have any of the following: a warning about disk size or errors with the auto-deleter"  or something like that, might be more accurate. 


It's hard to do this without introducing yet another query language. I vote for keeping it simple for the user. either it's all OR or all AND on patterns.

**Comment by gtk-grafana** [comment]
Closed by https://github.com/grafana/explore-logs/pull/419
