### ISSUE TITLE
exp: try smaller font in patterns table

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#366]
Try having the patterns text the same size as the log text. In theory, this font should be big enough for people to read it comfortably. Otherwise they might zoom in, in which case the patterns might get too big.

<img width="1557" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/30af346e-b931-44a2-a02b-da7f1b8b2233">

**Comment by zizzpudding** [comment]
It can be dropped down to 12pt Roboto Mono font and still be fine.  We might want to tighten up the table a bit if possible too so there isn't a lot of white space (maybe that was already done.
