### ISSUE TITLE
Add a search text box to quickly filter patterns by name

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#368]

**Comment by zizzpudding** [comment]
Are we giving users the ability to name patterns?  or do you mean that you can search for any substring of the pattern?  I'm not sure how useful a search is for patterns, but for consistency, I don't think it hurts. 

What might be more interesting is to have some criteria that users might want to use to search and filter (for instance some value > x, or in the case of patterns, count >, < or between, is the pattern trending up or down in volume over the time period, etc. )
