### ISSUE TITLE
Search service: We are loading only 100 services as default limit to /volume is 100 

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/explore-logs#374]
Related to internal feedback: https://raintank-corp.slack.com/archives/C05FWM2DN07/p1717067474805389

We are using /volume to get list of all service_names by volume, but loki uses default 100 limit here, so we are not showing all options: https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-log-volume

**Comment by svennergr** [comment]
What if we just increase the limit to 1000?
Any bad implications with that @cyriltovena @trevorgrafana?

**Comment by cyriltovena** [comment]
I think it might be time to add a services API :) so we can control how it works for our own use case.

**Comment by matryer** [comment]
@cyriltovena shall we raise the limit for now and schedule the new Services API?

**Comment by svennergr** [comment]
We added service search in https://github.com/grafana/explore-logs/pull/410 and believe it's good enough for now.
