### ISSUE TITLE
add ability to filter services by some labels (maybe just namespace?)

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/explore-logs#379]
we have not enabled our improved service detection in prod because of the just how big that would make our services, which are currently `team/component`. turning this on for prod would mean something like `loki/distributor` would include all ops and prod distributors, which would be a very big dataset. in order to allow us to turn improved service detection on for prod, we need some way to filter the initial page of services, at the very least by namespace.

this is very applicable to our environments, with varying applicability to others, so it should be optional.

I'm think a +namespace or +filter button or somewhere on the landing page of services to allow additional filtering.

we could start super opinionated and just offer an optional namespace filter, or we could be more generic and offer the top 5 labels based on number of streams they are found in (ie from `logcli series --analyze-labels`), or all labels found in every stream?

**Comment by svennergr** [comment]
let's follow this in https://github.com/grafana/explore-logs/issues/371
