### ISSUE TITLE
Collapsable log volume

### ISSUE THREAD

**Issue by zizzpudding** [grafana/explore-logs#386]
Would it be possible to collapse the Log volume so there is more room on the page for other data. 
Can we remove the "Logs" label above the logs table. It's redundant. The tab has the same name (see images below)
![markup](https://github.com/grafana/explore-logs/assets/573085/719b53d2-65b9-4280-8cd5-45b84dd089ec)

remove log label and collapse log volume
![collapsed_no_label](https://github.com/grafana/explore-logs/assets/573085/361fd425-4761-481c-801b-48aa1044d009)

collapsed log volume on patterns tab

![collapsed_volume_patterns](https://github.com/grafana/explore-logs/assets/573085/5f276444-321b-4090-986d-8b6e8bc78fab)

**Comment by matryer** [comment]
@zizzpudding we've just made a range of tweaks, including some of these. I'll ping you when it's updated so you can see the tweaks.

**Comment by matryer** [comment]
@@zizzpudding we've just done some tweaks including some of these, please do a hard refresh.

**Comment by gtk-grafana** [comment]
Doesn't look like scenes lets us pass the `collapsible`, `collapsed`, and `onToggleCollapse` props to the panel chrome. I'll take a quick look and see if we can propose a PR to add this to scenes.

**Comment by gtk-grafana** [comment]
Proposing allowing passthrough of PanelChrome props: https://github.com/grafana/scenes/pull/808

**Comment by zizzpudding** [comment]
How about if we do this? 

Video

https://github.com/user-attachments/assets/fd0ed872-da46-4622-8b72-f8b67b1585cc



Figma[https://www.figma.com/design/NT8kODiyLshr8S5WoXplIA/ExploreLogs?node-id=1672-1148&t=lCtTQDD52vYY1AOS-4](url)

**Comment by gtk-grafana** [comment]
Slack thread: https://raintank-corp.slack.com/archives/C05FWM2DN07/p1724786043784449?thread_ts=1724770788.256819&cid=C05FWM2DN07

I suggest we split out the collapsable issue from the error state issue, as we can make things collapsable on click right now with the proposed scenes changes above, but auto-collapsing based on query errors, and the custom error UI will need to be worked on in core grafana, working with the dashboards squad.
