### ISSUE TITLE
question: should we override ctrl+f and put focus into the nearby search box?

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#397]
When people do `ctrl+f` they are intending to 'find within this page'. Where we have paging (or infinite scroll) the content won't be visible on the page, and so they may think they are finding within all labels, but they aren't.

If we instead, pop them into the Search box

* UX: Are we ok to interrupt otherwise expected behaviour like this?
* Accessibility: Does this hurt here?

**Comment by zizzpudding** [comment]
For the most part Ctrl+F works as expected, even with infinite scrolling. I suggest not messing with the browser defaults, especially if we're not going to override it for all other Grafana apps. I'm not sure if there is an accessibility slant to this, but there might be. 

<img width="875" alt="image" src="https://github.com/grafana/explore-logs/assets/573085/ce060504-57e9-4586-b165-2f1541690a02">

**Comment by matyax** [comment]
We decided not to do this in Explore, and I think the same rationale applies to this app too. I would only consider it if we virtualize the list and cmd+f no longer works. For that, I proposed to do a custom search implementation to bridge that gap. Closing for clean up, feel free to reopen if there's pending discussion.
