### ISSUE TITLE
patterns: shorter display of Count

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#399]
Here we could say `40M`, `256k` etc. with hover for the real number.

<img width="219" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/310992ac-15b2-477e-b3e4-c5fefdab456b">

**Comment by zizzpudding** [comment]
I also suggest not putting the percentages in parens.  In accounting that means a negative number 
With a shortened count string, you can easily fit the percentage next to it 
![numbers](https://github.com/grafana/explore-logs/assets/573085/e2420ea3-dd68-410e-9967-63244ea4a9ff)
