### ISSUE TITLE
retry failed queries

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#413]
Sometimes queries fail but work after a refresh. So if the frontend retried a couple of times after a short delay, we will probably be ok.

---

sidenote: Francesc Campoy told me once that they would often make two of the same GET requests at the same time, and they just use whichever comes in first. (I'm not suggesting we do that, I don't think @cyriltovena would like it!)

**Comment by matryer** [comment]
update: a bug in the backend may address this. See https://github.com/grafana/loki/pull/13161

**Comment by gtk-grafana** [comment]
This should probably be addressed on the scenes side, and with consideration for overtaxing backend infra

**Comment by gtk-grafana** [comment]
@matyax has tackled this from the query sharding angle, closing
