### ISSUE TITLE
filter options should respect other selected filters or be cleared on change

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/explore-logs#416]
![Image](https://github.com/grafana/explore-logs/assets/469592/9167781e-7194-4eab-af99-0cdccde28dbf)

Since I have also have a namespace filter, I would expect my options for service to limited by those streams which also have `namespace=loki-ops`, especially since we don't clear the namespace selection when I select a different service. If we're going to keep the current behavior of not filtering options based on the other currently selected filters, then we probably have to clear all other filters on change?

I think the easier solution would be to limit options based on other selected filters.

**Comment by ivanahuckova** [comment]
The fix is in Loki data source and will be available once Grafana instance that users use has the fix.
