### ISSUE TITLE
Logs: allow filtering from logs volume

### ISSUE THREAD

**Issue by matyax** [grafana/explore-logs#422]
Use case: click on error levels in the volume chart, logs are filtered and updated by the selection.

![imagen](https://github.com/grafana/explore-logs/assets/1069378/8c388e90-92d5-47ae-9d52-4b3ea4ab4b85)

**Comment by svennergr** [comment]
Would we just filter in the frontend or do a new query? The issue with doing a new query is, that the volume legend would change, so I'm +1 for filtering.

**Comment by matryer** [comment]
@svennergr could you do a new query but NOT update the log volume graph? I.e. just do a new query in the logs panel?

**Comment by matyax** [comment]
The challenge of frontend filtering is that you might end up showing, e.g., 2 error lines when, for the selected time interval, you have 200 but were truncated by the response limit (1000 or 5000).

**Comment by svennergr** [comment]
Agree. On the other hand, the challenge with running new queries is that you might lose context.
Imagine the flow:
1. Filter for error logs
2. User found an interesting error log
3. Now the user wants to see info logs additionally to see the context of the error
4. Running a new query might lose context quite easily

And I think we are aligned that Log Context is the proper tool to do this, but still.
