### ISSUE TITLE
discussion: should we make pattern placeholders look different to `<_>`?

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#423]
> Feedback: I have a hard time visually identifying the patterns. It took me a while to under stand that <_> was a placeholder. Is it possible to signify this in some other way, with either color, font weight, underline or something of the sorts?

@matryer: I had the same idea during hackathon week, these are nice if you're working with queries etc. but in this context, they are difficult to interpret.

Idea:

What if we showed a selection of examples on hover? Or what if we picked an example to use as the placeholder, which again you could click and see other popular examples.

**Comment by cyriltovena** [comment]
100% we should find something that works better visually

**Comment by cyriltovena** [comment]
We could use LogQL to get a samples of values like [this](https://admin-dev-us-central-0.grafana-dev.net/grafana/explore?schemaVersion=1&panes=%7B%22ce4%22:%7B%22datasource%22:%22loki-dev%22,%22queries%22:%5B%7B%22refId%22:%22logs%22,%22expr%22:%22%7Bservice_name%3D%60loki%2Fdistributor%60%7D%20%7C%3E%20%60level%3Dinfo%20ts%3D%3C_%3E%20caller%3Dtee_service.go:250%20msg%3D%5C%22prepared%20Tee%20batches%20for%20tenant%5C%22%20tenant%3D%3C_%3E%20stream_count%3D%3C_%3E%20avg_logs_slice_cap_start%3D%3C_%3E%20avg_logs_slice_cap_end%3D%3C_%3E%20avg_logs_slice_len_end%3D%3C_%3E%20avg_log_lines_count%3D%3C_%3E%20avg_log_line_length%3D%3C_%3E%60%20%5Cn%7C%20pattern%20%60level%3Dinfo%20ts%3D%3C_%3E%20caller%3Dtee_service.go:250%20msg%3D%5C%22prepared%20Tee%20batches%20for%20tenant%5C%22%20tenant%3D%3Ctenant%3E%20stream_count%3D%3C_%3E%20avg_logs_slice_cap_start%3D%3C_%3E%20avg_logs_slice_cap_end%3D%3C_%3E%20avg_logs_slice_len_end%3D%3C_%3E%20avg_log_lines_count%3D%3C_%3E%20avg_log_line_length%3D%3C_%3E%60%20%5Cn%7C%20keep%20tenant%5Cn%7C%20line_format%20%5C%22%5C%22%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-dev%22%7D,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&orgId=1).


<img width="2528" alt="image" src="https://github.com/grafana/explore-logs/assets/1053421/71b89604-6ba7-40aa-9d5f-bf1e18e4c7a9">

**Comment by matryer** [comment]
Alternative proposal: (on the left)

![image (43)](https://github.com/grafana/explore-logs/assets/101659/8788232f-e572-4821-817c-dfae867f680d)
