### ISSUE TITLE
Ctrl+F find is not helpful with truncated values or names

### ISSUE THREAD

**Issue by zizzpudding** [grafana/explore-logs#488]
I was looking for a find on the request values breakdown, but since there isn't one there, I tried to use Ctrl+F to search the loaded values. 

Take a look at this video a request field. It has a large number of values and the values names are very long and truncated. If you try to do a search for a string hidden because the name is truncated, you can't tell which graph matches your search. 

Could we add a Search box at the top?

https://github.com/grafana/explore-logs/assets/573085/26affeb5-b358-4cb0-baca-a3c7ba97247d

**Comment by gtk-grafana** [comment]
Should be fixed now with https://github.com/grafana/explore-logs/pull/454
