### ISSUE TITLE
nit: clicking Detected Fields tab should jump back to first view

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#492]
Steps to reproduce:

1. Open **Explore > Logs** and go to **Detected Fields** ([like here](https://ops.grafana-ops.net/a/grafana-lokiexplore-app/explore?mode=service_details&var-filters=service_name%7C%3D%7Casserts%2Fmodel-builder&var-filters=level%7C%3D%7CERROR&actionView=fields&urlColumns=%5B%5D&visualizationType=%22logs%22&var-labelBy=$__all&var-fields=&var-fieldBy=$__all&from=now-3h&to=now&var-ds=000000193&var-patterns=&var-lineFilter=&var-logsFormat=%20%7C%20logfmt))
2. Select a value - you will go into the value view
3. Click **Detected fields** tab to go back - but you don't go back
4. Select another tab, and then choose **Detected fields** - this is the place we should go to from the value view

**Comment by gtk-grafana** [comment]
This was fixed with the recent routing addition: https://github.com/grafana/explore-logs/pull/606 (ignore the fact that PR is closed, github was having an incident when it was merged, but it is indeed merged)
