### ISSUE TITLE
Value breakdown sort improvements

### ISSUE THREAD

**Issue by matyax** [grafana/explore-logs#499]
- [ ] Sort has no impact on single view:
<img width="1712" alt="Pasted Graphic 1" src="https://github.com/grafana/explore-logs/assets/109082771/4a62d70b-1a83-4026-bb7f-2e580597d74e">

- [x] Row view appears broken and doesn't sort

- [ ] Can we add the calculated value to UI somewhere? E.g. the legend.

_Originally posted by @gtk-grafana in https://github.com/grafana/explore-logs/issues/479#issuecomment-2191818884_

**Comment by gtk-grafana** [comment]
Also the row view appears broken
