### ISSUE TITLE
Logs: error during the initial logs load after selecting a service

### ISSUE THREAD

**Issue by matyax** [grafana/explore-logs#524]
I noticed that, during the initial logs load after selecting a service, the logs query fails.

https://github.com/grafana/explore-logs/assets/1069378/192dc998-4d68-4cf9-8915-a28ba2a7cc9c

The error is:

![imagen](https://github.com/grafana/explore-logs/assets/1069378/264a0678-cbe6-4fdf-88f3-dfbe690ec9c6)

_Originally posted by @matyax in https://github.com/grafana/explore-logs/pull/518#pullrequestreview-2160438336_

**Comment by matryer** [comment]
@matyax is this still happening?

**Comment by matyax** [comment]
Yeah, I still see it.

**Comment by matyax** [comment]
This seems to be gone.
