### ISSUE TITLE
Labels: Empty state updates

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#529]
If we know there are some labels (from the count in the tab) but none are showing because of filters, what if we add a panel that says something like this:

```
[GROT pic]

No labels match these filters. Clear the filters to see all labels.
```

* `Clear the filters` could be a link that does just that

If there are no labels, I think this case is covered, but we should show a standard page, and link tot he docs to learn more.

<img width="1298" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/84f2091a-9f96-49e3-acad-5ba31fcc0f10">

* What other views does this apply to?
* related https://github.com/grafana/explore-logs/issues/536

**Comment by gtk-grafana** [comment]
Added in https://github.com/grafana/explore-logs/pull/572
