### ISSUE TITLE
Detected fields API error: Query too large

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#531]
![image](https://github.com/grafana/explore-logs/assets/109082771/72c6bc40-64de-487f-b1a8-c921562da86c)

@cyriltovena is this something we need to fix on the backend side, or is there something we can do in the frontend to prevent this?

**Comment by zizzpudding** [comment]
If we can't prevent it, can we please update the error message to make it more useful for app users. The error message has too much jargon for our target audience.

**Comment by svennergr** [comment]
Should be fixed by https://github.com/grafana/loki/pull/13423
