### ISSUE TITLE
Detected fields: warning notice when no fields available

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#536]
I think we can just have this as text on the page, or do what we do for other empty states explaining.

- [ ] Figure out what hint we can give people in this case

<img width="826" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/5b70da0d-7f77-45ac-9a97-25990b31f921">

**Comment by zizzpudding** [comment]
Is there a way to disable or remove the tab if there are no items under it?  

In Patterns we had a message to setup patterns, but this is different.  If we can't detect fields, we shouldn't show the tab.

**Comment by gtk-grafana** [comment]
Duplicate of https://github.com/grafana/explore-logs/issues/529

**Comment by gtk-grafana** [comment]
Actually no, need more coffee
