### ISSUE TITLE
log line: share URL to specific log line not always highlighting the line

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#560]
* Either fix the highlighting when following the URL, or
* Remove the copy icon feature for now (and we revisit after Public Preview)

**Comment by gtk-grafana** [comment]
Temporarily solved by https://github.com/grafana/explore-logs/pull/571.

Long term we'll need core changes needed by https://github.com/grafana/explore-logs/pull/568. And I still need to investigate the scrollTo bug.

**Comment by gtk-grafana** [comment]
Fixed with https://github.com/grafana/explore-logs/pull/568
