### ISSUE TITLE
Should the graphs automatically update themselves periodically?

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#576]
If you treat one of the views like a dashboard, you might like it to update.

What's the technical implication of this on the backend? Guess it's just like them refreshing every minute, which should be ok.

**Comment by gtk-grafana** [comment]
Already supported: https://play.grafana.org/a/grafana-lokiexplore-app/explore/service/tempo-distributor/labels?var-fields=&var-filters=service_name%7C%3D%7Ctempo-distributor&var-ds=ddhr3fttaw8aod&var-patterns=&var-lineFilter=&var-logsFormat=%20%7C%20logfmt&mode=service_details&urlColumns=%5B%5D&visualizationType=%22logs%22&var-labelBy=$__all&var-fieldBy=$__all&patterns=%5B%5D&from=now-5m&to=now&refresh=5s
