### ISSUE TITLE
Improve Labels queries performance

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#626]
Right now when doing labels queries they looks like this.

```
sum(count_over_time({service_name=`foo`}   | json   | drop __error__ | bar!="" | service_name=`foo` [20s])) by (bar)
```

This is very inefficient and causes a lot of resource usage. Instead we should make our queries performant by doing.

```
sum(count_over_time({service_name=`foo`,bar!=""} [20s])) by (bar)
```

**Comment by gtk-grafana** [comment]
Do we really need the `,bar!=""`? Can there be an empty stream selector?

**Comment by svennergr** [comment]
Label queries per se are fixed by https://github.com/grafana/explore-logs/pull/628
