### ISSUE TITLE
Filter for Field not showing up in logs panel details

### ISSUE THREAD

**Issue by miadabrin** [grafana/explore-logs#655]
Logs explorer with Loki source doesn't show icons to filter the fields .
<img width="1724" alt="image" src="https://github.com/user-attachments/assets/43c537ff-ef23-4994-a648-379d21607e9e">

I can see that it works in [play.grafana.org](https://play.grafana.org/) but I couldn't find any documentation on why these filters don't show up here. they do show up in `Open in Explore` though

**Comment by gtk-grafana** [comment]
@miadabrin I'm not able to reproduce this locally, are you running in Grafana cloud or on prem? If you're in cloud could you share your organization slug and let us know if we have your permission to temporarily access your instance?
CC: @matyax

**Comment by matyax** [comment]
It's very likely the underlying Grafana version.

**Comment by gtk-grafana** [comment]
Yeah good point, looks like we currently require grafana 11.0.0 or greater, but that's about to get increased to 11.1.1

**Comment by miadabrin** [comment]
@gtk-grafana it's on prem. I believe I have everything up to date. btw you can easily test this by running the docker-compose file in this repo. the fields are not filterable there either

**Comment by miadabrin** [comment]
@gtk-grafana @matyax .I just tested this by changing the grafana image to `main` and `GF_INSTALL_PLUGINS` to `https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-main.zip;grafana-lokiexplore-app` (`v0.1.3-437b058`) and it looks like to be fixed. so I guess we can expect this to be fixed when the new versions are released
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/81777720-39af-47c6-a564-3e6935be7b7d">
