### ISSUE TITLE
Aggregated Metrics frontend

### ISSUE THREAD

**Issue by svennergr** [grafana/explore-logs#689]
Do the necessary frontend changes for #688
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/explore-logs/issues/711
```

**Comment by trevorwhitney** [comment]
PR to use as starting place / inspiration: https://github.com/grafana/explore-logs/pull/625

**Comment by matyax** [comment]
Experimental feature. Use exploreLogsAggregatedMetrics if you want to try this. Work in progress as well
