### ISSUE TITLE
Labels breakdown: all labels added to the stream selector besides detected_field

### ISSUE THREAD

**Issue by matyax** [grafana/explore-logs#700]
One (maybe two) problems see:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/f80eec5a-78fe-4e20-a618-728cf4544a58">

All labels get added to the stream selector for the labels queries besides detected_field.

Looks like the queries in the labels panel are now ignoring the detected_level filters. in https://github.com/grafana/explore-logs/pull/682 I add a new method for adding custom structured metadata to queries without needing to interpolate. That might be helpful here?

_Originally posted by @gtk-grafana in https://github.com/grafana/explore-logs/issues/687#issuecomment-2298707778_

**Comment by gtk-grafana** [comment]
Looks like this is fixed by https://github.com/grafana/explore-logs/pull/682!

**Comment by gtk-grafana** [comment]
Can confirm this is no longer an issue, closing!
