### ISSUE TITLE
Allow case sensitive search

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#739]
Right now by default the search is case insensitive which can be expensive for Loki.

![Image](https://github.com/user-attachments/assets/2b80e4a0-08f8-46f6-bc7f-661603688340)

We should default to case sensitive search and provide a toggle to search between different mode like Vs code.

![Image](https://github.com/user-attachments/assets/f1ee4c61-1854-4216-a9d4-3b55015dfa37)

````
Aa => off |=  `...`  
           on |~ `(i?)…`
ab (whole word) => on |~ `\b...\b`
                                  off nothing
Not sure we want .*
````

The toggle is actually inside the text input.

**Comment by gtk-grafana** [comment]
@zizzpudding looks like we don't have any icons like this: https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-icon--icons-overview.

Would you be able to create a case-sensitive, and case-insensitive button for us to use here?

**Comment by gtk-grafana** [comment]
@cyriltovena I'm not sure we want to use word boundaries on one search and not the other, leads to unexpected results in the UI. For example `TRACE_TOO_LARGE` will return results when running `trace` as case insensitive search, but will not return results when running `TRACE` on case-sensitive search.

**Comment by gtk-grafana** [comment]
Also @cyriltovena if we ignore the word boundaries we can run `|= match` which should be a bit faster.
AND also I just realized you were proposing 2 bits of functionality, word boundaries AND case-sensitivity, and each button is a toggle, instead of case-sensitivity having two buttons. 🤦

**Comment by zizzpudding** [comment]
It sounds like you want to set Case Sensitivity by default for better performance, but the users who are going to see the benefit are a smaller percentage of our larger enterprise customers. I'm not sure we should be setting this default behavior and take away the benefit of a case sensitive search by default for the majority of users. 

The challenge I can see here is if the search is running slowly, we need to somehow hint that making it Case Sensitive will speed it up.

**Comment by gtk-grafana** [comment]
Agreed, after chatting with the squad we decided not to worry about word boundaries for now, and to default to the current case-insensitive search, which is going to be a better UX for most of our customers.
