### ISSUE TITLE
Make starting selector more flexible

### ISSUE THREAD

**Issue by stevendungan** [grafana/explore-logs#740]
We hear some of the following:
* I want to filter on something other than `service_name`
* I want to filter on something *in addition* to `service_name`
* `service_name` does not map well to my logging infrastructure and/or mental model

Explore options for making this more flexible for these users, to give them an effective way to quickly drill into relevant logs.

**Comment by aco-mreble** [comment]
For us it would be interesting to filter all services which contains e.g. `my-base-app`

**Comment by gtk-grafana** [comment]
Implemented in https://github.com/grafana/explore-logs/pull/813
