### ISSUE TITLE
Label values: No loading state for value breakdown when previous query returned error

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/explore-logs#785]
While the error message does update appropriately if a new error is received, and is removed when valid data is returned, there is no indication of the value breakdown query loading when in this error state.

![Image](https://github.com/user-attachments/assets/8081ab6f-5820-4265-94f3-2c562c04e473)

Also we should add some e2e coverage for these error states that are difficult to reproduce.

**Comment by matyax** [comment]
Fixed.
