### ISSUE TITLE
Fields view shows No Data for all detected fields since 1.0.0 (with loki)

### ISSUE THREAD

**Issue by davide-romanini-milkman** [grafana/explore-logs#812]
After upgrading to explore logs 1.0.0, we can't anymore use the fields view to drill down logs coming from our kubernetes services. The field view always shows `No data` for all detected fields.
![Image](https://github.com/user-attachments/assets/983e9a29-a8dc-4362-bf43-d7ce04e7e0f8)

The view was working fine with version 0.1.4.

Digging in the browser Network tab, I found the following:
 
 * The call to `detected_fields` endpoint sends a query including `json` and `logfmt`, eg: `{service_name="milkmansvc"} | json | logfmt | drop __error__, __error_details__`
 * The call to fetch aggregations for the single detected field no more includes the `json` and `logfmt` filters, causing the query to fetch no data, eg: `sum by (resources_k8s_deployment_name) (count_over_time({service_name="milkmansvc"} | resources_k8s_deployment_name!=""    [$__auto]))`

I verified in the raw Explore view that adding `json` to the query correctly fetches data for the field.
Of course I'm not sure if that is the actual culprit, but maybe it's a starting point.

Here are the versions of the grafana stack we are using:
* Grafana v11.2.0 (2a88694fd3)
* Explore logs plugin 1.0.1
* Loki 3.0.0

**Comment by gtk-grafana** [comment]
Hey @davide-romanini-milkman, as of the 1.0.0 release we [require Loki 3.2.0](https://github.com/grafana/explore-logs?tab=readme-ov-file#installation-in-your-own-grafana-instance) which provides support for the new detected_fields API we're using to get fields and structured metadata from Loki. 

Can you upgrade to Loki 3.2.0 and verify that fixes the problem?

**Comment by trevorwhitney** [comment]
@davide-romanini-milkman there was an issue with our release automation for version `6.17.0`. Version `6.18.0` has been released with Loki `3.2.0`
