### ISSUE TITLE
nit: No service matched your search when I've added 'database'

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#834]
Perhaps more general 'no data' text, also the tab hints that there would be some data but there isn't.

https://ops.grafana-ops.net/a/grafana-lokiexplore-app/explore?from=2024-10-17T13:13:16.201Z&to=2024-10-17T13:20:49.326Z&var-ds=c-R8UWvVk&patterns=%5B%5D&var-primary_label=database%7C%3D~%7C.%2B&var-filters=&var-fields=&var-levels=&var-patterns=&var-lineFilter=&refresh=

```
Nothing matches these filters,
please adjust or reset them.
```

![Image](https://github.com/user-attachments/assets/f020ec8e-d849-48c7-92df-9c903a496f79)

**Comment by gtk-grafana** [comment]
Good catch @matryer,

How does this copy look:
```No logs found in ${LABEL_NAME}, please adjust time range or select another label.```

or?

```No logs found in ${LABEL_NAME} for the provided time range, please adjust or select another label.```

 ![Image](https://github.com/user-attachments/assets/b2b2f791-1373-4f76-b843-37c5c71c4d1e)
