### ISSUE TITLE
Drill in to label and field values could have a more visual change

### ISSUE THREAD

**Issue by zizzpudding** [grafana/explore-logs#862]
I'ts easy to lose your place when you drill into a field or label to see the values. 
There are subtle changes on the screen but they are on your periphery and easy to miss. 
I've found myself lost more than a few times. 
https://github.com/user-attachments/assets/64f8afa5-5a17-497f-af9d-b96e426bc39f

**Comment by zizzpudding** [comment]
Here's a link to a figma design that could offer a solution. 
https://www.figma.com/design/HeugjX1FaRlT4svNWqizsj/Explore-logs---version-2-(Copy)?node-id=3045-29952&t=qdnncRYj0SCgsJPj-4

**Comment by gtk-grafana** [comment]
Mockup: ![Image](https://github.com/user-attachments/assets/e4acc97f-81d7-47a2-bd78-464372e79e19)
