### ISSUE TITLE
Logs level and pattern detection does not work with json format

### ISSUE THREAD

**Issue by suikast42** [grafana/explore-logs#869]
### What happened?

Explore logs from service selection

![Image](https://github.com/user-attachments/assets/ecf03ba2-9f60-4890-b695-d34d60f92150)

Explore logs in Explore

![Image](https://github.com/user-attachments/assets/9a4cd499-2d13-4ac5-8b02-86d15c2687b7)

### What did you expect to happen?

Explore logs does now show the right log levels and pattern detection does not works with json log format

**Comment by svennergr** [comment]
Hi @suikast42,

What Loki, Grafana, and Explore Logs plugin version are you running?

Thanks!

**Comment by suikast42** [comment]
The issue was  in my ingestion of the log data. I migrate to the new loki 3.2  client api and everything works fine.
