### ISSUE TITLE
service index page: Give user a way to make this work without service_name label

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#9]

**Comment by ivanahuckova** [comment]
@grafana/observability-logs reviewed and this should be probably driven by Loki team. So we are not adding it to GA project and leaving this up to Loki (fyi @cyriltovena/@trevorwhitney) to decide. From UI point, this shouldn't be complicated.

**Comment by gtk-grafana** [comment]
Closing, was added in https://github.com/grafana/explore-logs/pull/813
