### ISSUE TITLE
Log graph not showing up in Firefox (works in Safari)

### ISSUE THREAD

**Issue by Starefossen** [grafana/explore-logs#927]
The log graph is not showing up in Firefox but works in other browsers (tested in Safari).

Safari Version 18.1.1 (19619.2.8.111.7, 19619) on macOS

![Image](https://github.com/user-attachments/assets/e71ed3f6-d7d0-4b12-b816-212a39414956)

Firefox 134.0b2 (aarch64) on macOS

![Image](https://github.com/user-attachments/assets/e8b1623e-e6e9-477d-86fa-ed9080eff089)

* Grafana v11.3.1 (64b556c137)
* Explore Logs v1.0.4

**Comment by svennergr** [comment]
Thanks a lot for reporting this, @Starefossen! I can repro - https://github.com/grafana/explore-logs/pull/928 should fix this.
